/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package contactproject;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SOHAM
 */

public class Login extends javax.swing.JFrame {
Connection con;
static public int count=0;

public String getuserid()
{
return userid.getText();
}
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
   try{
        //Class.forName("sun.jdbc.odbc.JdbcOdbcDriver"); 
        //con=DriverManager.getConnection("jdbc:odbc:dsn");
        Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
       con=DriverManager.getConnection("jdbc:sqlserver://LAPTOP-OSE1P7NI:1433","sa","1234");
    } catch (SQLException |ClassNotFoundException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userid = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        AddLogin = new javax.swing.JButton();
        forgetpassword = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel1.setText("Password   :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 140, 119, 23);

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 14)); // NOI18N
        jLabel2.setText("User  ID     :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(74, 69, 112, 28);

        userid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                useridActionPerformed(evt);
            }
        });
        getContentPane().add(userid);
        userid.setBounds(252, 72, 118, 30);
        getContentPane().add(password);
        password.setBounds(252, 133, 118, 30);

        jLabel3.setFont(new java.awt.Font("Wide Latin", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("================LOGIN================");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 450, 66);

        login.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        login.setMnemonic('L');
        login.setText("LOGIN");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        getContentPane().add(login);
        login.setBounds(17, 206, 99, 36);

        AddLogin.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        AddLogin.setMnemonic('L');
        AddLogin.setText("NEW LOGIN");
        AddLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddLoginActionPerformed(evt);
            }
        });
        getContentPane().add(AddLogin);
        AddLogin.setBounds(134, 206, 120, 36);

        forgetpassword.setFont(new java.awt.Font("Yu Gothic Light", 1, 14)); // NOI18N
        forgetpassword.setMnemonic('L');
        forgetpassword.setText("Forgot Password?");
        forgetpassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgetpasswordActionPerformed(evt);
            }
        });
        getContentPane().add(forgetpassword);
        forgetpassword.setBounds(267, 206, 157, 36);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/contactproject/contact icon.jpg"))); // NOI18N
        jLabel4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-6, -6, 460, 310);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void useridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_useridActionPerformed
      
    }//GEN-LAST:event_useridActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
    try {
        ResultSet rscount;
        Statement s=con.createStatement();
        s.executeUpdate("use PROFILECONTACT");
        rscount=s.executeQuery("select count(*) as count from ALLCONTACTS ");
        if(rscount.next())
        {
        if(rscount.getInt("count")>0)
        {
            
            try {
                
                ResultSet rs;
                s.execute("use PROFILECONTACT;");
                rs=s.executeQuery("select FULLNAME from ALLCONTACTS where userid='"+userid.getText()+"' and password='"+new String(password.getPassword())+"'");
                if(rs.next())
                {
                    JOptionPane.showMessageDialog(rootPane, "Welcome"+rs.getString("FULLNAME")+"\n  You have Successfully LOGGED IN !!!!");
                    NewjFrame2 frame2 = new NewjFrame2(userid.getText(),new String(password.getPassword()));
                    s.close();
                     rs.close();
                    this.setVisible(false);
                    frame2.setVisible(true);
                    login.setVisible(false);
                    
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "Login Problem,\n Username and Password do not match");
                }
               
            } catch (SQLException ex) {
                Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            
            JOptionPane.showMessageDialog(null, "NO LOGIN EXISTS HERE \n CREATE A NEW LOGIN");
        }
            rscount.close();
        }
      rscount.close();
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }
    
    }//GEN-LAST:event_loginActionPerformed

    private void AddLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddLoginActionPerformed
        login.setVisible(false);
        NewjFrame2 frame3 = new NewjFrame2();
        frame3.setVisible(true);
     /*   try {
        ResultSet rscount;
        Statement s=con.createStatement();
        s.executeUpdate("use PROFILECONTACTS");
        s.executeUpdate("create table "+userid.getText()+"(
        userid varchar(25),
        password varchar (25),
        fullname varchar(100),
        phone varchar(15),
        address varchar(1000),
         photojpg varbinary(max),
         dob varchar(20), 
        email varchar(20), 
        notes varchar(2000), 
        forgetpassword varchar(1000)  )");
          if(count==0)
        {    try{
       
        
        
        
        } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        }
        else
        {
        contactprofile frame3 = new contactprofile();
        login.setVisible(false);
        frame3.setVisible(true);
        
        }
    } catch (SQLException ex) {
        Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
    }*/
    }//GEN-LAST:event_AddLoginActionPerformed
        
    private void forgetpasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgetpasswordActionPerformed
       changepassword frame5 = new changepassword(userid.getText());
        frame5.setVisible(true);
        frame5.setSize(500, 350);
    }//GEN-LAST:event_forgetpasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Login frame1 = new Login();
                frame1.setSize(450, 300);
                frame1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddLogin;
    private javax.swing.JButton forgetpassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField userid;
    // End of variables declaration//GEN-END:variables
}
